/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Business.Contribuinte;
import Business.DeclaracaoCompleta;
import Persistence.CadastroDeclaracao;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class Interface extends javax.swing.JFrame {

      
    private boolean arquivoCarregado = false;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeArquivoTextField = new javax.swing.JTextField();
        Passo1 = new javax.swing.JLabel();
        EnviarArquivo = new javax.swing.JButton();
        NomeArquivoText = new javax.swing.JLabel();
        Passo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomeArquivoTextField.setText("contribuintes.txt");
        nomeArquivoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeArquivoTextFieldActionPerformed(evt);
            }
        });

        Passo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Passo1.setText("Escolha o Arquivo");

        EnviarArquivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EnviarArquivo.setText("Enviar Arquivo");
        EnviarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarArquivoActionPerformed(evt);
            }
        });

        NomeArquivoText.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NomeArquivoText.setText("Nome do Arquivo:");

        Passo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Passo2.setText("Carregar Contribuintes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(Passo2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(NomeArquivoText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeArquivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Passo1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EnviarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Passo2)
                .addGap(14, 14, 14)
                .addComponent(Passo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeArquivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeArquivoText)
                    .addComponent(EnviarArquivo))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeArquivoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeArquivoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeArquivoTextFieldActionPerformed

    private void EnviarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarArquivoActionPerformed
        lerArquivo(nomeArquivoTextField.getText());        
    }//GEN-LAST:event_EnviarArquivoActionPerformed

    private void lerArquivo(String filename) {                
        Contribuinte contribuinte;
        DeclaracaoCompleta declaracaoCompleta;
        CadastroDeclaracao cadastroDeclaracao = new CadastroDeclaracao();
        try {
            Scanner sc = new Scanner(new File(filename));
            sc.useDelimiter(";");
            while (sc.hasNext()) {
                String nome = sc.next();
                System.out.println(nome);
                String cpf = sc.next();
                System.out.println(cpf);
                int idade = sc.nextInt();
                System.out.println(idade);
                int numDepen = sc.nextInt();
                System.out.println(numDepen);
                double totalRend = Double.parseDouble(sc.next());
                System.out.println(totalRend);                
                double contriOficial = Double.parseDouble(sc.next());;                
                System.out.println(contriOficial);
                contribuinte = new Contribuinte(nome, cpf, idade, 
                        numDepen, totalRend, contriOficial);
                declaracaoCompleta = new DeclaracaoCompleta(contribuinte);
                cadastroDeclaracao.incluirDeclaracao(declaracaoCompleta);                
            }
            sc.close();
            System.out.println(cadastroDeclaracao.toString());
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(null,
                    "Arquivo não encontrado!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarArquivo;
    private javax.swing.JLabel NomeArquivoText;
    private javax.swing.JLabel Passo1;
    private javax.swing.JLabel Passo2;
    private javax.swing.JTextField nomeArquivoTextField;
    // End of variables declaration//GEN-END:variables
}
